### PR TITLE
Medieval

### PR DESCRIPTION
**Pull request by dranikpg**
Simple skin for Scene2D !
Includes a cursor image !
This skin works super for me , and I think this will be a good skin-theme, wich fits perfect to this collection !

### CODE REVIEW

**Comment by czyzby** [comment]
It looks like you used [Kenney's RPG UI pack](http://opengameart.org/content/ui-pack-rpg-extension), it would be nice to mention that.

Could you include the raw assets you used to create the skin? If you look at the other skin directories, you'll notice that they all follow a similar pattern:

```
> raw
   > *.png
> skin
   > *.atlas
   > *.png (packed atlases)
   > *.fnt
   > *.json
> preview.png
> README.md
```

Your current folder structure is, well, flat. And raw assets are not included. Please, reorganize your skin first. You also have to add a license and links to the original authors (Kenney and whoever made that font you used).

You might also want to look into [ninepatches](https://github.com/libgdx/libgdx/wiki/Ninepatches) or [tiled drawables](http://www.badlogicgames.com/forum/viewtopic.php?f=17&t=22075), which allow your images to be resized without losing quality. Some of your widgets look a little blurred, and I can only imagine this effect gets worse as they are scaled up.

**Comment by dranikpg** [comment]
Is it okay yet ?

**Comment by czyzby** [comment]
The folder structure is OK, but I don't think the quality of this skin is fine just yet. Correct me if I'm wrong, but it seems that you basically took Kenney's assets and used them without much (any?) modifications. If you want anyone to use your skin, you have to add any extra features and actually show some effort to make it worthwhile - otherwise people might just use the original assets and create skins/atlases that suit them best. For example, [Kenney atlases](https://github.com/czyzby/gdx-skins/tree/master/kenney) are separated by color for convenience and converted to ninepatches, while [pixel Kenney skin](https://github.com/czyzby/gdx-skins/tree/master/kenney-pixel) can be recolored with a single JSON line.

Your assets are blurred when resized and most images are, well, too small _not to be_ resized in production. Changing some of your drawables to [ninepatches](https://github.com/libgdx/libgdx/wiki/Ninepatches) would make your skin much easier to scale correctly. Please, read some [articles](https://pimentoso.blogspot.com/2013/04/libgdx-scene2d-skin-quick-tutorial.html) about [preparing Scene2D skins](http://www.gamefromscratch.com/post/2013/12/18/LibGDX-Tutorial-9-Scene2D-Part-3-UI-Skins.aspx) first, then correct your skin and upload it again.

**Comment by dranikpg** [comment]
Second version:)

**Comment by czyzby** [comment]
It's definitely better, ninepatches _do_ make a difference.

Any particular reason why there are 4 atlas images? Seems like one should be enough to store them all. Does the skin need so many fonts?

**Comment by dranikpg** [comment]
I used ray's skin packer ... So I don't know ... 
I always packed skins this way ...

**Comment by raeleus** [comment]
It's making more atlas pages because you're using too much texture space. Don't make so many fonts and don't create your fonts in Hiero. Hiero wastes tons of space making the font texture as a power of 2. Use Littera or Shoebox and deactivate POT.

**Comment by czyzby** [comment]
Oh, I thought it was a bug and created [this issue](https://github.com/raeleus/skin-composer/issues/7). You might still look into your texture packer settings - you can safely use `stripWhitespace` in most GUI skins.

**Comment by raeleus** [comment]
I'll investigate. Do you know offhand if it preserves the dimensions if I, for example, purposely want empty space around an image?

**Comment by dranikpg** [comment]
Is it a big problem ?

**Comment by czyzby** [comment]
Drawables (and sprites) supplied by texture atlases store the stripped whitespace sizes and draw the regions with appropriate offsets. The images still report the correct sizes and basically act as if they had the whitespace in the first place. If you use texture regions directly though, you might lose the offsets data if I'm correct.

@DranikProgrammer - not really, it's just inefficient.

**Comment by raeleus** [comment]
Having multiple atlas pages is a problem. It will perform slower and lower end devices won't be able to run it. Especially if they combine it with their game textures.

**Comment by raeleus** [comment]
Thanks for the info Czyzby.

**Comment by dranikpg** [comment]
I really like yor work , wich makes libgdx alive , actually I'm a student who likes programming , so thanks for your help !

**Comment by czyzby** [comment]
Not sure if you're referring to me, but hey - not a problem. Fix your atlas and I'll accept the pull request.

**Comment by dranikpg** [comment]
I'm referring to both , english uses two times you , sorry for that misconseption .

**Comment by czyzby** [comment]
Heh, that's why I always throw in something in plural form like "guys" at the end to avoid the confusion.

Anyway, you can use texture packer [directly](https://github.com/libgdx/libgdx/wiki/Texture-packer) until Raeleus looks into packer options in his application.

**Comment by raeleus** [comment]
Thanks for the comments Dranik!

**Review by czyzby — CHANGES_REQUESTED** [review]
Use a single atlas image.

**Comment by dranikpg** [comment]
Oh sorry, I'll fix it as soon as possible...

**Comment by czyzby** [comment]
@raeleus has already addressed the atlas images issue in his Skin Composer, you should [check it out](https://github.com/raeleus/skin-composer/issues/7).

**Comment by tehnewb** [comment]
> Simple skin for Scene2D !
> Includes a cursor image !
> This skin works super for me , and I think this will be a good skin-theme, wich fits perfect to this collection !

Would be nice if it supported the default VisUI skin!

**Comment by czyzby** [comment]
I'm closing this due to the issue with the atlases. If you'd still like to contribute the skin or any other resources, please create a separate pull request.

**Pull request closed without merging**
